#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>

#include <QMainWindow>


QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; } // this is a forward declaration; it is automatically generated by qt
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget* parent = nullptr);
    ~MainWindow();

protected:

private:
    // this is the version with a smart pointer; it can also be non-pointer;
    std::unique_ptr<Ui::MainWindow> ui = std::make_unique<Ui::MainWindow>();
};
#endif // MAINWINDOW_H
